language: objective-c
osx_image: xcode8.2
install: echo
before_install:
  - gem install xcpretty
  - mkdir -p ~/Library/Logs/DiagnosticReports
script:
  - diskutil erasevolume HFS+ 'pxctest' `hdiutil attach -nomount ram://4194304`
  - df -h
  - ls -la /Volums/pxctest
  - exit 1
  - set -o pipefail
  - scripts/bootstrap.sh
  - NSUnbufferedIO=YES xcodebuild -scheme pxctest test | xcpretty -c
  - brew tap plu/pxctest && brew install pxctest --HEAD && pxctest version
